version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: messagehub-db
    environment:
      - POSTGRES_USER=myadmin
      - POSTGRES_PASSWORD=secret123
      - POSTGRES_DB=messagehub
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
